server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboottest
    username: root
    password: nothing000
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat,wall
      aop-patterns: com.example..springboot2.*
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
  redis:
    host: 39.101.67.172
    port: 6379
    client-type: jedis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
